### PR TITLE
windows build testing

### LINKED ISSUE #2: Windows: not run
**Reverse-FFI**

```bash
run reverse-ffi: error: the following command exited with error code 53:
D:\a\lean4-zig\lean4-zig\zig-out\bin\reverse-ffi.exe 
Build Summary: 4/6 steps succeeded; 1 failed (disable with --summary none)
rffi transitive failure
+- run reverse-ffi failure
error: the following build command failed with exit code 1:
D:\a\lean4-zig\lean4-zig\zig-cache\o\b87e9cba7a4b935a9aaebbed0a78c850\build.exe C:\hostedtoolcache\windows\zig\0.11.0\x64\zig.exe D:\a\lean4-zig\lean4-zig D:\a\lean4-zig\lean4-zig\zig-cache C:\Users\runneradmin\AppData\Local\zig rffi -freference-trace -freference-trace
```
Missing `libleanshared.dll` on `$PATH`?

### PR DESCRIPTION
**Pull request by digama0**
fixes #2 (hopefully). @kassane Can you test this? I don't have a windows machine.

### CODE REVIEW

**Comment by kassane** [comment]
The bug reported in #6 appears to be striking again.
https://github.com/kassane/lean4-zig/actions/runs/6031601521/job/16366051089?pr=8#step:7:13 (re-run w/ debug CI)

I'm presuming this is running at run-time and isn't showing a possible path to the library `libleanshared.dll.a`
https://github.com/kassane/lean4-zig/blob/4d4f8bff9970c6ea1ae9c093c7c3318464fd510c/build.zig#L43
or
https://github.com/kassane/lean4-zig/blob/b78a8157ee28ac085e3257a477f58b8411054454/build.zig#L44-L45

`linkSystemLibraryName` gives the name of the library for zig to rename possible combinations.

**Comment by kassane** [comment]
~~Please! Turn this PR in draft.~~ The changes are good. The problem is caused in the toolchain mainstream.

> I don't have a windows machine.

Also, I'm not a Windows user but I want to do some tests in a VM.

I thought about using msys2 in the CI to make using environment variables (`msystem`) easier. However, lean4 is not included in the packages yet. e.g.: https://github.com/kassane/qml_zig/blob/main/.github/workflows/MSYS.yml

**Comment by digama0** [comment]
Feel free to push to this PR if you have other ideas, I'm all out. If it's a toolchain bug we might just be stuck.

**Comment by kassane** [comment]
> Feel free to push to this PR if you have other ideas, I'm all out. If it's a toolchain bug we might just be stuck.

Ok!

One question: Is it possible in lakescript create a branch condition on a string libraryname depending on the operating system?

Like it:
```zig
// build.zig
const libname = switch(target.getOsTag()) {
    .windows => "mylib.lib",
// ignore anywhere os specific
    else => "mylib.a",
};
```

**Comment by kassane** [comment]
Finally build test and rffi works:
https://github.com/kassane/lean4-zig/actions/runs/6041224247/job/16393706583?pr=8#step:8:5
```bash
Run zig build test --summary all -freference-trace
Build Summary: 3/3 steps succeeded; 1/1 tests passed
test success
+- run lean_test 1 passed 7ms MaxRSS:4M
   +- zig test lean_test Debug native success 1m MaxRSS:206M
```

but, get on zffi lake build error.

**Comment by digama0** [comment]
> One question: Is it possible in lakescript create a branch condition on a string libraryname depending on the operating system?

Yes, `if System.Platform.isWindows then ... else if System.Platform.isOSX then ... else ...`

**Comment by kassane** [comment]
Thanks for help!

**Pull request merged**
